### PR TITLE
Add version info from git tags

### PR DESCRIPTION
**Pull request by AliAlbarrak**
This plugin does exactly what we need for our work flow but we relay on git tags for versioning internal code.
Added latest tag to git info.

### CODE REVIEW

**Comment by crotwell** [comment]
Not opposed to including the tag, but should it be included if it is older? Perhaps only include the tag if it is --exact-match?

Concern is that including a tag that was for an older release might be confusing. Thoughts?

**Comment by alaa13212** [comment]
I tried to write the command in a way that doesn't throw errors or break the build if the git repo doesn't include any tags, for backward compatibility with other plugin users.


If the repo included tags but current commit doesn't, the format will be `{lastTag}-{n}-g{hash}`
      where `n`  is the number of commits since `lastTag`

Otherwise the format will be `{tag}` only.
If no tags at all where present it will fall back to `{hash}`


Using `--exact-match` will cause the command to fail with fatal error in some cases.

**Comment by AliAlbarrak** [comment]
I tried to write the command in a way that doesn't throw errors or break the build if the git repo doesn't include any tags, for backward compatibility with other plugin users.

If the repo included tags but current commit doesn't,
the format will be `{lastTag}-{n}-g{hash}` where `n` is the number of commits since `lastTag`

Otherwise the format will be `{tag}` only.
If no tags at all where present it will fall back to {hash}

Using `--exact-match` will cause the command to fail with fatal error in some cases.

**Comment by crotwell** [comment]
Ok, agree --exact-match seems problematic. I don't see your recent changes in the PR.

Should this be opt-in, as perhaps not everyone would want tags printed? Not sure if that might leak information people might not want to publish.

Perhaps instead of a special format for old tags, could it record separate fields for the last tag, its commit hash, date of last tag and number of commits since last tag? So if num is zero you know tag is at the commit, and if not you know how old and could find the exact commit?

Maybe also good to call it "lastTag" instead of "tagVersion" as tags can be used for many things besides versions.

thoughts?

**Comment by AliAlbarrak** [comment]
Committed separate fields for last tag, its date and number of commits since the tag. As you suggested, it is more versatile that way.

For compatibility, I made sure the command don't cause fetal errors for different cases.
If there are no tags in the repo, git command will output and the current commit, date of that commit and 0 for commits since.

**Comment by crotwell** [comment]
Looks good, thanks for the PR.
Plugin is published as 1.4.0

**Pull request merged**
